source "http://rubygems.org"

gem 'rails', "3.2.13"

gem 'pg'

gem 'jquery-rails'

gem 'haml-rails'
gem 'simple_form'

group :assets  do 
	
end

group :development do 
	gem "rspec", "2.13"
	gem "rspec-rails", "2.13"
end	
group :test do 
	gem "rspec", "2.13"
	gem "rspec-rails", "2.13"
	gem "rspec-core", "2.13"
	gem "rspec-expectations", "2.13"
	gem "rspec-mocks", "2.13"
	gem "database_cleaner"
	gem "spork"
	gem "capybara"
end

