common: &common
  adapter: postgresql
  username: rails
  password: password
  port: 5432
  host: localhost

development:
  <<: *common
  database: rails_development

test:
  <<: *common
  database: rails_test

production:
  <<: *common
  database: rails_prod
